import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: ["100","300","400", "500", "700", "900"] });

export const metadata = {
  title: "Shlen Power",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
